#!/bin/bash
sudo mke2fs -m 0 /dev/ram0
sudo mkdir /mnt/rd1
mount /dev/ram0 /mnt/rd1

mke2fs -m 0 /dev/ram1
sudo mkdir /mnt/rd2
mount /dev/ram1 /mnt/rd2

mke2fs -m 0 /dev/ram2
sudo mkdir /mnt/rd3
mount /dev/ram2 /mnt/rd3

mke2fs -m 0 /dev/ram3
sudo mkdir /mnt/rd4
mount /dev/ram3 /mnt/rd4

mke2fs -m 0 /dev/ram4
sudo mkdir /mnt/rd5
mount /dev/ram4 /mnt/rd5

mke2fs -m 0 /dev/ram5
sudo mkdir /mnt/rd6
mount /dev/ram5 /mnt/rd6
